# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version.
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "spotify"
  # Box from "https://spotify.box.com/vagrant-box-debian-squeeze-64"

  config.vm.hostname = 'ngn-vagrant'

  config.vm.provision :shell, :path => "bootstrap.sh"

  config.ssh.forward_agent = true

  config.ssh.private_key_path = "/Users/niklas/.ssh/id_rsa"

  config.vm.synced_folder "/Users/niklas/.m2", "/home/vagrant/.m2"
  config.vm.synced_folder "/Users/niklas/src", "/home/vagrant/src"
  config.vm.synced_folder "/Users/niklas/Downloads", "/home/vagrant/Downloads"

  config.vm.provider :virtualbox do |vb|
    vb.name = "spotify"
    vb.customize ["modifyvm", :id, "--memory", "1024"]
  end
end
